title: 24lutego
description: moj przykładowy dokument
theme: just-the-docs

url: https://katgaj.github.io/24lutego

aux_links:
  Template Repository: https://github.com/katgaj/24lutego


  # Set a path/url to a logo that will be displayed instead of the title
  # logo: ""C:\KT\GIT\24lutego\images\skilogo_76x76.png""
